// Deploy a default chess game.
// This is mostly done so that the Chess Game ABI and artifacts are generated by hardhat-deploy
import { DeployFunction, DeployResult } from "hardhat-deploy/dist/types";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { network, ethers } from "hardhat";
import {
  KnightTokens,
  BishopTokens,
  KingTokens,
  QueenTokens,
  RookTokens,
  PawnTokens,
} from "src/types/tokens";

import { ChessPieceProperties, PieceClass } from "@src/types";

const deployChessPieceCollection: DeployFunction = async (
  hre: HardhatRuntimeEnvironment
) => {
  const { deploy } = hre.deployments;
  const { deployer } = await hre.getNamedAccounts();
  const chainId = network.config.chainId!;
  const owner = await ethers.getSigner(deployer);

  const deployResult: DeployResult = await deploy("ChessGame", {
    from: deployer,
    log: true,
    args: [deployer, deployer, deployer, deployer],
    waitConfirmations: chainId == 31337 ? 1 : 6,
  });
};

export default deployChessPieceCollection;
deployChessPieceCollection.tags = ["all", "game", "chessGame"];
